-- YOUR CODE GOES HERE
-- CREATE YOUR DATABASE
-- CREATE YOUR TABLES
-- ADD RECORDS TO YOUR TABLE
DROP DATABASE IF EXISTS cows;
CREATE DATABASE cows;
USE cows;
CREATE TABLE cows (
  _id INT PRIMARY KEY AUTO_INCREMENT,
  cow_name VARCHAR(20),
  cow_description VARCHAR(100)
);